const int RESISTIEF_DROOG_INTERVAL_MIN = 0;
const int RESISTIEF_DROOG_INTERVAL_MAX = 2178;

const int RESISTIEF_VOCHTIG_INTERVAL_MIN = 2179;
const int RESISTIEF_VOCHTIG_INTERVAL_MAX = 2543;

const int RESISTIEF_NAT_INTERVAL_MIN = 2544;
const int RESISTIEF_NAT_INTERVAL_MAX = 3000;

