const int RESISTIEF_DROOG_INTERVAL_MIN = 0;
const int RESISTIEF_DROOG_INTERVAL_MAX = 2178;

const int RESISTIEF_VOCHTIG_INTERVAL_MIN = 2179;
const int RESISTIEF_VOCHTIG_INTERVAL_MAX = 2543;

const int RESISTIEF_NAT_INTERVAL_MIN = 2544;
const int RESISTIEF_NAT_INTERVAL_MAX = 3000;

const int CAPACITIEF_DROOG_INTERVAL_MIN = 3200;
const int CAPACITIEF_DROOG_INTERVAL_MAX = 2303;

const int CAPACITIEF_VOCHTIG_INTERVAL_MIN = 2302;
const int CAPACITIEF_VOCHTIG_INTERVAL_MAX = 1802;

const int CAPACITIEF_NAT_INTERVAL_MIN = 1801;
const int CAPACITIEF_NAT_INTERVAL_MAX = 1000;

const float MINIMUM_TEMPERATUUR = 5.0;
const float EXTRA_WATER_TEMPERATUUR = 25.0;